public class Data{
    /*
    AVOID CHANGING PLAYER DETAILS.
    MAKE THE CHANGE ONLY AFTER A GAME IS OVER.

    CREATE A BOOLEAN FOR EACH INPUT FROM PLAYER
    ifUSERINPUTTED
    ifUSERSELECTEDMAZE
    ifUSERFINISHEDMAZE

        if(ifUSERINPUTTED $&& ifUSERSELECTEDMAZE &&  ifUSERFINISHEDMAZE) //HAS TO BE ALL TRUE
        {OUTPUT INTO THE DATA TXT FILE}
        else{
         DO NOT WRITE ANYTHING TO THE FILE AND DISPOSE THE VALUES STORED INTO THOSE LOCAL VARIABLES }

        ACCESS THE DATA TXT FILE WHEN USER SELECTS VIEW SCORE
        THAT CLASS WILL READ THE DATA TXT FILE AND OUTPUT THE EXISITING SCORES
        BASED ON

        NAME LEVEL SCORE


        QUICK NOTE

        CONDITIONS OF WHEN THE GAME ENDS
        IF TIME == 00;
        REST TIME EVERYTIME A NEW MAP IS SELECTED.
        WHEN PLAYER CLOSES THE WINDOW OR CLICKS NEW MAP BUTTON
        IF(TIME RUNS OUT or IFPLAYERTOUCHESREDFINISHLINE)
        THAT IS WHEN ifUSERFINISHMAZE = TRUE;

        IF PLAYER EXITS
     */
}
